#ifndef DEFINES_H_INCLUDED
#define DEFINES_H_INCLUDED

#define N_OF_OBJECTS 50
#define N_CHAR_MAX 32
#define P_AT_READING 1
#define P_AT_LEARNING 3
#define P_AT_CREATION 3
#define T_CREATIVE_SEC 5
#define T_CREATIVE_N 3

#endif // DEFINES_H_INCLUDED